{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2aa8edc4-64a8-4a8a-a762-7ad7fe2de366",
   "metadata": {},
   "outputs": [],
   "source": [
    "# imd_api_wrapper/app.py\n",
    "# ─────────────────────────────────────────────────────────────\n",
    "# Main entry point — paste each CELL into JupyterHub one by one.\n",
    "# This file covers the full workflow:\n",
    "#   1. Setup and imports\n",
    "#   2. Cluster → API mapping table\n",
    "#   3. Individual endpoint tests\n",
    "#   4. Full profile (all 6 at once)\n",
    "#   5. Query router (text → endpoint)\n",
    "#   6. Batch routing of KCC-style queries\n",
    "#   7. Summary DataFrames and CSV exports\n",
    "# ─────────────────────────────────────────────────────────────\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# CELL 1 — Install dependencies (run once)\n",
    "# ============================================================\n",
    "\n",
    "# !pip install requests pandas\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# CELL 2 — Add project root to path so wrapper imports work\n",
    "# ============================================================\n",
    "\n",
    "import sys, os\n",
    "sys.path.insert(0, os.path.abspath(\"..\"))   # adjust if needed\n",
    "\n",
    "import json\n",
    "import pandas as pd\n",
    "import logging\n",
    "\n",
    "logging.basicConfig(level=logging.INFO, format=\"%(levelname)s %(message)s\")\n",
    "\n",
    "print(\"Path configured.\")\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# CELL 3 — Import everything from the wrapper package\n",
    "# ============================================================\n",
    "\n",
    "from wrapper import (\n",
    "    IMDClient,\n",
    "    route_query,\n",
    "    route_batch,\n",
    "    get_endpoint_for_cluster,\n",
    "    get_endpoint_for_need,\n",
    "    get_full_mapping_table,\n",
    "    get_need_summary,\n",
    ")\n",
    "\n",
    "client = IMDClient()\n",
    "print(\"IMDClient ready.\")\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# CELL 4 — Full cluster → API mapping table (all 59 clusters)\n",
    "# Shows every cluster, its farmer need, and recommended endpoint\n",
    "# ============================================================\n",
    "\n",
    "mapping_rows = get_full_mapping_table()\n",
    "mapping_df   = pd.DataFrame(mapping_rows)\n",
    "\n",
    "mapping_df = mapping_df[[\n",
    "    \"cluster_id\",\n",
    "    \"farmer_need\",\n",
    "    \"endpoint_key\",\n",
    "    \"priority\",\n",
    "    \"freshness_minutes\",\n",
    "    \"cluster_queries\",\n",
    "    \"cluster_coverage_pct\",\n",
    "    \"need_queries\",\n",
    "    \"need_coverage_pct\",\n",
    "]]\n",
    "\n",
    "mapping_df = mapping_df.sort_values(\"cluster_queries\", ascending=False)\n",
    "mapping_df.to_csv(\"cluster_api_mapping_full.csv\", index=False)\n",
    "\n",
    "print(f\"Cluster-API mapping saved → cluster_api_mapping_full.csv\")\n",
    "print(f\"Total clusters: {len(mapping_df)}\")\n",
    "print(f\"Total queries represented: {mapping_df['cluster_queries'].sum():,}\")\n",
    "print()\n",
    "mapping_df.head(15)\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# CELL 5 — Farmer need summary (6 needs from 15.5M queries)\n",
    "# ============================================================\n",
    "\n",
    "need_rows = get_need_summary()\n",
    "need_df   = pd.DataFrame(need_rows)\n",
    "\n",
    "need_df.to_csv(\"farmer_need_summary.csv\", index=False)\n",
    "print(\"Farmer need summary saved → farmer_need_summary.csv\\n\")\n",
    "need_df\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# CELL 6 — Endpoint for a specific cluster\n",
    "# ============================================================\n",
    "\n",
    "cluster_id = 3    # ← change to any cluster 0-58\n",
    "\n",
    "info = get_endpoint_for_cluster(cluster_id)\n",
    "print(f\"Cluster {cluster_id} details:\")\n",
    "for k, v in info.items():\n",
    "    print(f\"  {k:<25} {v}\")\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# CELL 7 — Endpoint for a specific farmer need\n",
    "# ============================================================\n",
    "\n",
    "need = \"Rain Forecast\"   # ← change as needed\n",
    "\n",
    "info = get_endpoint_for_need(need)\n",
    "print(f\"Farmer need: {need}\")\n",
    "for k, v in info.items():\n",
    "    print(f\"  {k:<25} {v}\")\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# CELL 8 — CRITICAL: 7-day city forecast\n",
    "# Covers General Weather Forecast (cluster 3,18,28,27,58…)\n",
    "# 13,706,092 queries = 88.15% of all weather queries\n",
    "# ============================================================\n",
    "\n",
    "print(\"=== CRITICAL | City 7-Day Forecast: Delhi ===\\n\")\n",
    "result = client.get_city_forecast(city=\"Delhi\", state=\"Delhi\")\n",
    "print(json.dumps(result, indent=2, default=str))\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# CELL 9 — HIGH: district forecast\n",
    "# Covers District Weather Forecast (cluster 54,36,41,8,9…)\n",
    "# 1,335,570 queries = 8.59%\n",
    "# ============================================================\n",
    "\n",
    "print(\"=== HIGH | District Forecast: Aligarh, Uttar Pradesh ===\\n\")\n",
    "result = client.get_district_forecast(district=\"Aligarh\", state=\"Uttar Pradesh\")\n",
    "print(json.dumps(result, indent=2, default=str))\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# CELL 10 — MEDIUM: rainfall forecast\n",
    "# Covers Rain Forecast (cluster 20, 2, 4, 42, 19)\n",
    "# 248,633 queries = 1.60%\n",
    "# ============================================================\n",
    "\n",
    "print(\"=== MEDIUM | Rainfall Forecast: Nashik, Maharashtra (5 days) ===\\n\")\n",
    "result = client.get_rainfall_forecast(\n",
    "    district=\"Nashik\", state=\"Maharashtra\", days=5\n",
    ")\n",
    "print(json.dumps(result, indent=2, default=str))\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# CELL 11 — MEDIUM: current weather\n",
    "# Covers Current Weather Condition (cluster 35, 29, 11)\n",
    "# 180,855 queries = 1.16%\n",
    "# ============================================================\n",
    "\n",
    "print(\"=== MEDIUM | Current Weather: Mumbai ===\\n\")\n",
    "result = client.get_current_weather(city=\"Mumbai\", state=\"Maharashtra\")\n",
    "print(json.dumps(result, indent=2, default=str))\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# CELL 12 — LOW: nowcast\n",
    "# Covers Short Term Forecast (cluster 24, 23)\n",
    "# 57,084 queries = 0.37%\n",
    "# ============================================================\n",
    "\n",
    "print(\"=== LOW | Nowcast: Nagpur, Maharashtra ===\\n\")\n",
    "result = client.get_nowcast(district=\"Nagpur\", state=\"Maharashtra\")\n",
    "print(json.dumps(result, indent=2, default=str))\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# CELL 13 — LOW: agro-met advisory\n",
    "# Covers Weather Impact on Crops (cluster 5, 51)\n",
    "# 21,655 queries = 0.14%\n",
    "# ============================================================\n",
    "\n",
    "print(\"=== LOW | Agromet Advisory: Pune, Maharashtra (Paddy) ===\\n\")\n",
    "result = client.get_agromet_advisory(\n",
    "    district=\"Pune\", state=\"Maharashtra\", crop=\"Paddy\"\n",
    ")\n",
    "print(json.dumps(result, indent=2, default=str))\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# CELL 14 — Full profile: all 6 endpoints in one call\n",
    "# ============================================================\n",
    "\n",
    "print(\"=== FULL PROFILE: Delhi / Aligarh, Uttar Pradesh ===\\n\")\n",
    "\n",
    "profile = client.get_full_profile(\n",
    "    city     = \"Delhi\",\n",
    "    district = \"Aligarh\",\n",
    "    state    = \"Uttar Pradesh\",\n",
    "    crop     = \"Wheat\",\n",
    ")\n",
    "\n",
    "for ep, data in profile.items():\n",
    "    status = \"ERROR\" if \"error\" in data else \"OK\"\n",
    "    print(f\"  [{status}] {ep}\")\n",
    "\n",
    "print()\n",
    "print(json.dumps(profile, indent=2, default=str))\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# CELL 15 — Query router: text → endpoint\n",
    "# Simulates how a KCC call-centre query gets routed\n",
    "# ============================================================\n",
    "\n",
    "test_queries = [\n",
    "    \"what is the weather tomorrow\",\n",
    "    \"will it rain in my district tomorrow\",\n",
    "    \"weather forecast for next 5 days in my block\",\n",
    "    \"current weather condition today\",\n",
    "    \"rainfall information in Aligarh\",\n",
    "    \"crop damage due to heavy rain compensation\",\n",
    "    \"barish kab hogi\",\n",
    "    \"weather report in west midnapur district\",\n",
    "    \"frost protection for mustard crop\",\n",
    "    \"weather in hisar\",\n",
    "    \"tell me weather information\",\n",
    "    \"weather forecast of block tappal in district aligarh\",\n",
    "]\n",
    "\n",
    "print(\"=== QUERY ROUTER TEST ===\\n\")\n",
    "for q in test_queries:\n",
    "    r = route_query(q)\n",
    "    print(f\"  Query   : {q}\")\n",
    "    print(f\"  Need    : {r['farmer_need']}\")\n",
    "    print(f\"  Endpoint: {r['endpoint_key']}  |  Priority: {r['priority']}\")\n",
    "    print(f\"  Keyword : {r['matched_keyword']}\")\n",
    "    print()\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# CELL 16 — Batch routing (all queries at once)\n",
    "# ============================================================\n",
    "\n",
    "route_results = route_batch(test_queries)\n",
    "route_df      = pd.DataFrame(route_results)\n",
    "route_df.to_csv(\"query_routing_results.csv\", index=False)\n",
    "\n",
    "print(\"Routing results saved → query_routing_results.csv\\n\")\n",
    "route_df\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# CELL 17 — Full profile summary as a clean DataFrame\n",
    "# ============================================================\n",
    "\n",
    "profile = client.get_full_profile(\n",
    "    city     = \"Delhi\",\n",
    "    district = \"Aligarh\",\n",
    "    state    = \"Uttar Pradesh\",\n",
    "    crop     = \"Wheat\",\n",
    ")\n",
    "\n",
    "rows = []\n",
    "for ep, data in profile.items():\n",
    "    from wrapper.config import PRIORITY, FRESHNESS_MINUTES, FARMER_NEED\n",
    "    rows.append({\n",
    "        \"Endpoint\"        : ep,\n",
    "        \"Farmer Need\"     : FARMER_NEED.get(ep, \"\"),\n",
    "        \"Priority\"        : PRIORITY.get(ep, \"\"),\n",
    "        \"Freshness (min)\" : FRESHNESS_MINUTES.get(ep, \"\"),\n",
    "        \"Status\"          : \"ERROR\" if \"error\" in data else \"OK\",\n",
    "        \"Temperature C\"   : data.get(\"temperature_c\"),\n",
    "        \"Rainfall mm\"     : data.get(\"rainfall_mm\"),\n",
    "        \"Humidity %\"      : data.get(\"humidity_pct\"),\n",
    "        \"Wind km/h\"       : data.get(\"wind_speed_kmh\"),\n",
    "        \"Alert\"           : data.get(\"alert_type\", \"\"),\n",
    "        \"Condition\"       : data.get(\"condition\", \"\"),\n",
    "    })\n",
    "\n",
    "summary_df = pd.DataFrame(rows)\n",
    "summary_df.to_csv(\"full_profile_summary.csv\", index=False)\n",
    "\n",
    "print(\"Summary saved → full_profile_summary.csv\\n\")\n",
    "summary_df\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# CELL 18 — Priority distribution chart\n",
    "# ============================================================\n",
    "\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "need_df = pd.DataFrame(get_need_summary())\n",
    "\n",
    "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n",
    "\n",
    "# Bar chart — query volume per need\n",
    "axes[0].barh(\n",
    "    need_df[\"farmer_need\"],\n",
    "    need_df[\"total_queries\"],\n",
    "    color=[\"#D85A30\",\"#1D9E75\",\"#378ADD\",\"#378ADD\",\"#888780\",\"#888780\"],\n",
    ")\n",
    "axes[0].set_xlabel(\"Total Queries\")\n",
    "axes[0].set_title(\"Query Volume per Farmer Weather Need (15.5M KCC dataset)\")\n",
    "axes[0].invert_yaxis()\n",
    "\n",
    "# Pie chart — % coverage\n",
    "axes[1].pie(\n",
    "    need_df[\"total_queries\"],\n",
    "    labels=need_df[\"farmer_need\"],\n",
    "    autopct=\"%1.1f%%\",\n",
    "    startangle=140,\n",
    ")\n",
    "axes[1].set_title(\"Coverage Distribution\")\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.savefig(\"query_distribution.png\", dpi=150, bbox_inches=\"tight\")\n",
    "plt.show()\n",
    "print(\"Chart saved → query_distribution.png\")\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# CELL 19 — Going LIVE (instructions for when you get IMD key)\n",
    "# ============================================================\n",
    "\n",
    "print(\"\"\"\n",
    "HOW TO GO LIVE\n",
    "══════════════\n",
    "1. Open  imd_api_wrapper/wrapper/client.py\n",
    "2. Change lines 19-20:\n",
    "       BASE_URL = \"https://imdapi.met.gov.in\"   ← real IMD URL\n",
    "       API_KEY  = \"your-real-api-key-here\"\n",
    "3. In the _fetch() function (line ~65):\n",
    "       - Delete the MOCK block\n",
    "       - Uncomment the LIVE block (~10 lines)\n",
    "4. Re-run from Cell 2. Nothing else changes.\n",
    "\n",
    "To request IMD API access:\n",
    "   Portal : https://mausam.imd.gov.in\n",
    "   Email  : helpdesk@imd.gov.in\n",
    "\"\"\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
