{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ce3955c0-17af-4962-ae3c-c8d72071b00e",
   "metadata": {},
   "outputs": [],
   "source": [
    "# imd_api_wrapper/run_api.py\n",
    "# ─────────────────────────────────────────────────────────────\n",
    "# Paste each CELL into JupyterHub to install, start, and test\n",
    "# the FastAPI server — all from inside the notebook.\n",
    "# ─────────────────────────────────────────────────────────────\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# CELL 1 — Install FastAPI and Uvicorn (run once)\n",
    "# ============================================================\n",
    "\n",
    "!pip install fastapi uvicorn httpx requests\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# CELL 2 — Start the FastAPI server in the background\n",
    "# The server runs on port 8000 inside JupyterHub.\n",
    "# Output is written to api_server.log so it does not flood\n",
    "# the notebook.\n",
    "# ============================================================\n",
    "\n",
    "import subprocess\n",
    "import time\n",
    "import os\n",
    "\n",
    "log_file = open(\"api_server.log\", \"w\")\n",
    "\n",
    "server = subprocess.Popen(\n",
    "    [\n",
    "        \"uvicorn\",\n",
    "        \"api.main:app\",\n",
    "        \"--reload\",\n",
    "        \"--host\", \"0.0.0.0\",\n",
    "        \"--port\", \"8000\",\n",
    "    ],\n",
    "    stdout=log_file,\n",
    "    stderr=log_file,\n",
    "    cwd=os.path.abspath(\".\")   # must be inside imd_api_wrapper/\n",
    ")\n",
    "\n",
    "time.sleep(3)   # give uvicorn a moment to start\n",
    "\n",
    "if server.poll() is None:\n",
    "    print(\"FastAPI server started  →  http://localhost:8000\")\n",
    "    print(\"Swagger docs            →  http://localhost:8000/docs\")\n",
    "    print(\"ReDoc                   →  http://localhost:8000/redoc\")\n",
    "    print(\"Logs                    →  api_server.log\")\n",
    "else:\n",
    "    print(\"Server failed to start. Check api_server.log:\")\n",
    "    with open(\"api_server.log\") as f:\n",
    "        print(f.read())\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# CELL 3 — Test health check\n",
    "# ============================================================\n",
    "\n",
    "import requests, json\n",
    "\n",
    "BASE = \"http://localhost:8000\"\n",
    "\n",
    "resp = requests.get(f\"{BASE}/\")\n",
    "print(\"Status:\", resp.status_code)\n",
    "print(json.dumps(resp.json(), indent=2))\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# CELL 4 — Test CRITICAL: city forecast\n",
    "# ============================================================\n",
    "\n",
    "resp = requests.get(f\"{BASE}/weather/city-forecast\", params={\n",
    "    \"city\" : \"Delhi\",\n",
    "    \"state\": \"Delhi\",\n",
    "})\n",
    "print(\"Status:\", resp.status_code)\n",
    "print(json.dumps(resp.json(), indent=2))\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# CELL 5 — Test HIGH: district forecast\n",
    "# ============================================================\n",
    "\n",
    "resp = requests.get(f\"{BASE}/weather/district-forecast\", params={\n",
    "    \"district\": \"Aligarh\",\n",
    "    \"state\"   : \"Uttar Pradesh\",\n",
    "})\n",
    "print(\"Status:\", resp.status_code)\n",
    "print(json.dumps(resp.json(), indent=2))\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# CELL 6 — Test MEDIUM: rainfall forecast\n",
    "# ============================================================\n",
    "\n",
    "resp = requests.get(f\"{BASE}/weather/rainfall-forecast\", params={\n",
    "    \"district\": \"Nashik\",\n",
    "    \"state\"   : \"Maharashtra\",\n",
    "    \"days\"    : 5,\n",
    "})\n",
    "print(\"Status:\", resp.status_code)\n",
    "print(json.dumps(resp.json(), indent=2))\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# CELL 7 — Test MEDIUM: current weather\n",
    "# ============================================================\n",
    "\n",
    "resp = requests.get(f\"{BASE}/weather/current\", params={\n",
    "    \"city\" : \"Mumbai\",\n",
    "    \"state\": \"Maharashtra\",\n",
    "})\n",
    "print(\"Status:\", resp.status_code)\n",
    "print(json.dumps(resp.json(), indent=2))\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# CELL 8 — Test LOW: nowcast\n",
    "# ============================================================\n",
    "\n",
    "resp = requests.get(f\"{BASE}/weather/nowcast\", params={\n",
    "    \"district\": \"Nagpur\",\n",
    "    \"state\"   : \"Maharashtra\",\n",
    "})\n",
    "print(\"Status:\", resp.status_code)\n",
    "print(json.dumps(resp.json(), indent=2))\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# CELL 9 — Test LOW: agromet advisory\n",
    "# ============================================================\n",
    "\n",
    "resp = requests.get(f\"{BASE}/weather/agromet-advisory\", params={\n",
    "    \"district\": \"Pune\",\n",
    "    \"state\"   : \"Maharashtra\",\n",
    "    \"crop\"    : \"Paddy\",\n",
    "})\n",
    "print(\"Status:\", resp.status_code)\n",
    "print(json.dumps(resp.json(), indent=2))\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# CELL 10 — Test: full profile (all 6 at once)\n",
    "# ============================================================\n",
    "\n",
    "resp = requests.get(f\"{BASE}/weather/full-profile\", params={\n",
    "    \"city\"    : \"Delhi\",\n",
    "    \"district\": \"Aligarh\",\n",
    "    \"state\"   : \"Uttar Pradesh\",\n",
    "    \"crop\"    : \"Wheat\",\n",
    "})\n",
    "print(\"Status:\", resp.status_code)\n",
    "print(json.dumps(resp.json(), indent=2))\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# CELL 11 — Test: query router (single)\n",
    "# ============================================================\n",
    "\n",
    "test_queries = [\n",
    "    \"will it rain tomorrow in my district\",\n",
    "    \"weather forecast for next 5 days\",\n",
    "    \"current weather condition today\",\n",
    "    \"crop damage due to heavy rainfall\",\n",
    "    \"barish kab hogi\",\n",
    "    \"weather in hisar\",\n",
    "    \"tell me weather information\",\n",
    "    \"frost protection for mustard crop\",\n",
    "    \"weather forecast of block tappal in district aligarh\",\n",
    "    \"rainfall information in Nashik\",\n",
    "]\n",
    "\n",
    "print(\"=== Single Query Routing ===\\n\")\n",
    "for q in test_queries:\n",
    "    resp = requests.get(f\"{BASE}/router/query\", params={\"q\": q})\n",
    "    r    = resp.json()\n",
    "    print(f\"  Query   : {q}\")\n",
    "    print(f\"  Need    : {r['farmer_need']}\")\n",
    "    print(f\"  Endpoint: {r['endpoint_key']}  |  Priority: {r['priority']}\")\n",
    "    print()\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# CELL 12 — Test: query router (batch POST)\n",
    "# ============================================================\n",
    "\n",
    "resp = requests.post(\n",
    "    f\"{BASE}/router/batch\",\n",
    "    json=test_queries,\n",
    ")\n",
    "print(\"Status:\", resp.status_code)\n",
    "print(json.dumps(resp.json(), indent=2))\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# CELL 13 — Test: analysis endpoints\n",
    "# ============================================================\n",
    "\n",
    "# Cluster info\n",
    "resp = requests.get(f\"{BASE}/analysis/cluster/3\")\n",
    "print(\"=== Cluster 3 ===\")\n",
    "print(json.dumps(resp.json(), indent=2))\n",
    "\n",
    "# Farmer need info\n",
    "resp = requests.get(\n",
    "    f\"{BASE}/analysis/need/Rain Forecast\"\n",
    ")\n",
    "print(\"\\n=== Farmer Need: Rain Forecast ===\")\n",
    "print(json.dumps(resp.json(), indent=2))\n",
    "\n",
    "# All farmer needs summary\n",
    "resp = requests.get(f\"{BASE}/analysis/needs\")\n",
    "print(\"\\n=== All Farmer Needs ===\")\n",
    "print(json.dumps(resp.json(), indent=2))\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# CELL 14 — Test: full cluster mapping table\n",
    "# ============================================================\n",
    "\n",
    "import pandas as pd\n",
    "\n",
    "resp = requests.get(f\"{BASE}/analysis/mapping\")\n",
    "data = resp.json()\n",
    "\n",
    "mapping_df = pd.DataFrame(data[\"mapping\"])\n",
    "mapping_df.to_csv(\"api_cluster_mapping.csv\", index=False)\n",
    "\n",
    "print(f\"Total clusters : {data['total_clusters']}\")\n",
    "print(f\"Total queries  : {data['total_queries_covered']:,}\")\n",
    "print(f\"Saved           → api_cluster_mapping.csv\\n\")\n",
    "mapping_df.head(15)\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# CELL 15 — Check server logs (if anything looks wrong)\n",
    "# ============================================================\n",
    "\n",
    "with open(\"api_server.log\") as f:\n",
    "    print(f.read()[-3000:])   # last 3000 chars\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# CELL 16 — Stop the server (run when done)\n",
    "# ============================================================\n",
    "\n",
    "server.terminate()\n",
    "print(\"FastAPI server stopped.\")\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# CELL 17 — Full project structure reference\n",
    "# ============================================================\n",
    "\n",
    "print(\"\"\"\n",
    "PROJECT STRUCTURE\n",
    "═════════════════\n",
    "imd_api_wrapper/\n",
    "├── api/\n",
    "│   └── main.py               ← FastAPI app (all routes)\n",
    "├── wrapper/\n",
    "│   ├── __init__.py           ← Package exports\n",
    "│   ├── config.py             ← KCC analysis constants (59 clusters)\n",
    "│   ├── api_mapping.py        ← Cluster → need → endpoint logic\n",
    "│   ├── client.py             ← IMDClient (6 methods, mock + live)\n",
    "│   └── router.py             ← Text query → endpoint router\n",
    "├── app.py                    ← Direct Python / Jupyter usage\n",
    "├── run_api.py                ← This file (FastAPI Jupyter runner)\n",
    "└── requirements.txt\n",
    "\n",
    "API ROUTES\n",
    "══════════\n",
    "GET  /                              Health check\n",
    "GET  /health                        Detailed health\n",
    "\n",
    "GET  /weather/city-forecast         CRITICAL  88.15% of KCC queries\n",
    "GET  /weather/district-forecast     HIGH       8.59%\n",
    "GET  /weather/rainfall-forecast     MEDIUM     1.60%\n",
    "GET  /weather/current               MEDIUM     1.16%\n",
    "GET  /weather/nowcast               LOW        0.37%\n",
    "GET  /weather/agromet-advisory      LOW        0.14%\n",
    "GET  /weather/full-profile          ALL        100%\n",
    "\n",
    "GET  /router/query?q=...            Route single query text\n",
    "POST /router/batch                  Route list of query texts\n",
    "\n",
    "GET  /analysis/cluster/{id}         Cluster metadata\n",
    "GET  /analysis/need/{need}          Farmer need metadata\n",
    "GET  /analysis/mapping              All 59 clusters table\n",
    "GET  /analysis/needs                All 6 farmer needs summary\n",
    "\n",
    "DOCS\n",
    "════\n",
    "Swagger UI  →  http://localhost:8000/docs\n",
    "ReDoc       →  http://localhost:8000/redoc\n",
    "\"\"\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
